/*
 * Created by SharpDevelop.
 * User: suloku
 * Date: 27/02/2016
 * Time: 16:17
 *
 * To change this template use Tools | Options | Coding | Edit Standard Headers.
 */
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Windows.Forms;
using System.IO;

using System.Reflection;
using System.Resources;

namespace BW_tool
{

	/// <summary>
	/// Description of Grotto.
	/// </summary>
	public partial class Grotto : Form
	{
		ResourceManager resources = new ResourceManager("BW_tool.Grotto", Assembly.GetExecutingAssembly());

/* Hidden Grottoes ("kemonomichi" / animal trail) - BW2

	Layout taken from the game's own savedata/etc_save.c:

	  typedef struct{
	    u16 is_set      :1;   // an object is placed here
	    u16 table_index :4;   // which of the 11 rank tables (ANIMAL_TRAIL_TABLE_NUM)
	    u16 data_index  :3;   // which of the 4 entries in that table (DATA_TABLE_LEN)
	    u16 female_num  :7;   // gender roll, 0-99
	    u16 pad         :1;
	  }ANIMAL_TRAIL_DATA;

	  typedef struct {
	    ANIMAL_TRAIL_DATA trail_data[20];  // ANIMAL_TRAIL_NUM, at 0xCC in the ETC block
	    u8 now_trail_id;                   // 0xF4, grotto the game last entered
	    u8 padding[3];
	  }ANIMAL_TRAIL_SAVE;

	sc_obj_type_table maps table_index to what gets placed:
	  0-2  -> AT_OBJ_TYPE_MONSTER
	  3-6  -> AT_OBJ_TYPE_ITEM
	  7-10 -> AT_OBJ_TYPE_HIDE_ITEM (dowsing)
	  11-15 are out of range and are never generated by the game.

	female_num is rolled with GFUser_GetPublicRand(100), so 0-99. The placed
	pokemon is FEMALE when female_num < female_probability for that table entry,
	otherwise male. The game's own debug script commands set it to 0 to force
	female and 100 to force male.

	A grotto is re-rolled every 256 steps with a 5/256 chance
	(ANIMAL_TRAIL_SELECT_WALK_CNT / ANIMAL_TRAIL_SELECT_PROBABILITY).
*/

		//Block indices, in save_tbl.c (GMDATA_ID) order
		public const int GROTTO_BLOCK   = 66; //GMDATA_ID_ETC     - _ETC_SAVE_WORK
		public const int ENCOUNT_BLOCK  = 55; //GMDATA_ID_ENCOUNT - ENC_SV_DATA

		//_ETC_SAVE_WORK / ANIMAL_TRAIL_SAVE
		public const int TRAIL_OFFSET   = 0xCC; //ANIMAL_TRAIL_DATA trail_data[20]
		public const int TRAIL_COUNT    = 20;   //ANIMAL_TRAIL_NUM
		public const int NOW_TRAIL_ID_OFFSET = TRAIL_OFFSET + (TRAIL_COUNT * 2); //0xF4

		//ENC_SV_DATA
		public const int SWARM_OFFSET   = 0x2C; //GenerateZoneIdx

		//Values the game itself uses for the "force gender" debug commands
		public const int FEMALE_ROLL_FORCE_FEMALE = 0;
		public const int FEMALE_ROLL_FORCE_MALE   = 100;

		byte[] grottobuffer;
		byte[] encountbuffer;

		int currentTrail = -1; //grotto currently shown in the controls
		bool loading = false;  //suppresses control events while repopulating

		public Grotto()
		{
			//
			// The InitializeComponent() call is required for Windows Forms designer support.
			//
			InitializeComponent();

			//Whole block regions, so they can be handed back to setBlock() later.
			//setBlock() recalculates the block CRC, the CRC table and the CRC
			//table's own checksum, and mirrors everything into the backup save.
			grottobuffer  = MainForm.save.getBlock(GROTTO_BLOCK);
			encountbuffer = MainForm.save.getBlock(ENCOUNT_BLOCK);

			loadSwarmData();
			loadNowTrailData();

			//Fires Grotto_routeSelectedIndexChanged, which loads grotto 0
			Grotto_route.SelectedIndex = 0;
		}

		//----------------------------------------------------------------------
		// ANIMAL_TRAIL_DATA accessors
		//----------------------------------------------------------------------
		ushort getTrail(int index)
		{
			return BitConverter.ToUInt16(grottobuffer, TRAIL_OFFSET + (index * 2));
		}
		void setTrail(int index, ushort value)
		{
			BitConverter.GetBytes(value).CopyTo(grottobuffer, TRAIL_OFFSET + (index * 2));
		}
		static bool trail_is_set(ushort data)
		{
			return (data & 0x0001) != 0;
		}
		static int trail_table_index(ushort data)
		{
			return (data >> 1) & 0x0F;
		}
		static int trail_data_index(ushort data)
		{
			return (data >> 5) & 0x07;
		}
		static int trail_female_num(ushort data)
		{
			return (data >> 8) & 0x7F;
		}
		static ushort trail_pack(bool is_set, int table_index, int data_index, int female_num, ushort original)
		{
			ushort data = (ushort)(original & 0x8000); //keep the pad bit as we found it
			if (is_set) data |= 0x0001;
			data |= (ushort)((table_index & 0x0F) << 1);
			data |= (ushort)((data_index  & 0x07) << 5);
			data |= (ushort)((female_num  & 0x7F) << 8);
			return data;
		}

		//----------------------------------------------------------------------
		// Grotto
		//----------------------------------------------------------------------
		void loadGrottoData(int index)
		{
			if (index < 0 || index >= TRAIL_COUNT) return;

			ushort data = getTrail(index);

			loading = true;

			//table_index is 4 bits and normalgrottobox has all 16 entries, so this
			//can never fall out of range
			normalgrottobox.SelectedIndex = trail_table_index(data);

			//data_index is 3 bits but only 0-3 are ever generated (DATA_TABLE_LEN)
			int group = trail_data_index(data);
			if (group >= normalgrottogroupbox.Items.Count) group = 0;
			normalgrottogroupbox.SelectedIndex = group;

			normalgrottoavailable.Checked = trail_is_set(data);

			int roll = trail_female_num(data);
			if (roll > (int)femalebox.Maximum) roll = (int)femalebox.Maximum;
			femalebox.Value = roll;

			loading = false;

			updategenders();
		}
		void storeGrottoData(int index)
		{
			if (index < 0 || index >= TRAIL_COUNT) return;

			ushort original = getTrail(index);
			setTrail(index, trail_pack(
				normalgrottoavailable.Checked,
				normalgrottobox.SelectedIndex      < 0 ? 0 : normalgrottobox.SelectedIndex,
				normalgrottogroupbox.SelectedIndex < 0 ? 0 : normalgrottogroupbox.SelectedIndex,
				(int)femalebox.Value,
				original));
		}

		//----------------------------------------------------------------------
		// now_trail_id
		//----------------------------------------------------------------------
		void loadNowTrailData()
		{
			int now = grottobuffer[NOW_TRAIL_ID_OFFSET];
			if (now >= lastgrottobox.Items.Count) now = 0;
			lastgrottobox.SelectedIndex = now;
		}
		void storeNowTrailData()
		{
			grottobuffer[NOW_TRAIL_ID_OFFSET] =
				(byte)(lastgrottobox.SelectedIndex < 0 ? 0 : lastgrottobox.SelectedIndex);
		}

		//----------------------------------------------------------------------
		// Swarm (GenerateZoneIdx)
		//----------------------------------------------------------------------
		void loadSwarmData()
		{
			int swarm = encountbuffer[SWARM_OFFSET];
			//encpoke_GetGenerateData() clamps anything >= GENERATE_ENC_POKE_MAX to 0
			if (swarm >= swarmbox.Items.Count) swarm = 0;
			swarmbox.SelectedIndex = swarm;
		}
		void storeSwarmData()
		{
			encountbuffer[SWARM_OFFSET] =
				(byte)(swarmbox.SelectedIndex < 0 ? 0 : swarmbox.SelectedIndex);
		}

		//----------------------------------------------------------------------
		// Gender preview
		//----------------------------------------------------------------------
		void updategenders()
		{
			//The pokemon is female when female_num < female_probability, see
			//scrcmd_animal_trail.c. The four columns are the female ratios the
			//grotto tables actually use.
			int roll = (int)femalebox.Value;
			gender5.Text  = (roll <  5) ? "F" : "M";
			gender10.Text = (roll < 10) ? "F" : "M";
			gender30.Text = (roll < 30) ? "F" : "M";
			gender60.Text = (roll < 60) ? "F" : "M";
		}
		void FemaleboxValueChanged(object sender, EventArgs e)
		{
			if (loading) return;
			updategenders();
		}

		//----------------------------------------------------------------------
		// Events
		//----------------------------------------------------------------------
		void Grotto_routeSelectedIndexChanged(object sender, EventArgs e)
		{
			//Commit whatever is on screen before moving to another grotto,
			//otherwise edits are lost when switching routes
			storeGrottoData(currentTrail);

			currentTrail = Grotto_route.SelectedIndex;
			loadGrottoData(currentTrail);

			table_but.Enabled = (currentTrail > -1);
		}
		void Save_buttonClick(object sender, EventArgs e)
		{
			storeGrottoData(currentTrail);
			storeNowTrailData();
			storeSwarmData();

			//setBlock() fixes the block checksum, the CRC table entry, the CRC
			//table's own checksum and the backup save copy for us
			MainForm.save.setBlock(grottobuffer,  GROTTO_BLOCK);
			MainForm.save.setBlock(encountbuffer, ENCOUNT_BLOCK);

			this.Close();
		}
		void LastvisitedhelpClick(object sender, EventArgs e)
		{
			MessageBox.Show("now_trail_id: the grotto the game last entered. If you saved inside a hidden grotto and change this value, loading the save will place you in the selected grotto instead.\n\nBeware you can get stuck if you don't have the HM moves needed to leave that grotto.");
		}
		void FemalehelpClick(object sender, EventArgs e)
		{
			MessageBox.Show("Gender roll (female_num in the save structure).\n\n" +
			                "The game rolls this value 0-99 when the grotto is regenerated. " +
			                "When the grotto holds a pokemon, it is FEMALE if this value is lower than that pokemon's female ratio, and male otherwise.\n\n" +
			                "The Gender box shows the outcome for the four female ratios the grotto tables use. " +
			                "Force Female sets 0 and Force Male sets 100, which is exactly what the game's own debug commands do.\n\n" +
			                "It has no effect on grottoes holding an item.");
		}
		void ForceFemale_butClick(object sender, EventArgs e)
		{
			femalebox.Value = FEMALE_ROLL_FORCE_FEMALE;
		}
		void ForceMale_butClick(object sender, EventArgs e)
		{
			femalebox.Value = FEMALE_ROLL_FORCE_MALE;
		}
		void Note_butClick(object sender, EventArgs e)
		{
			MessageBox.Show("Note: if you have saved inside a grotto that holds a pokemon and change the slot to an item, you can still trigger the battle after reloading. In that case you will battle a level 1 Gurdurr, which isn't a pokemon available at hidden grottoes.\n\nSlots 11-15 are never generated by the game (only 11 tables exist) and are left in the list for research only.");
		}
		void Black2table_butClick(object sender, EventArgs e)
		{
			Form form = new Form();

			PictureBox pictureBox = new PictureBox();
			try
			{
				pictureBox.Dock = DockStyle.Fill;
				pictureBox.Image = (Bitmap)resources.GetObject("b2_" + Grotto_route.SelectedIndex);
				pictureBox.SizeMode = PictureBoxSizeMode.StretchImage;
				form.Controls.Add(pictureBox);
				Size size = new Size(720, 300);
				form.Size = size;
				form.Show();
			}
			catch (System.IO.FileNotFoundException)
			{
				MessageBox.Show("There was an error opening the table.\n" +
					"Please check you have included grotto_tables folder in the same path as BW_tool.exe.");
			}
		}
		void Grotto_helpClick(object sender, EventArgs e)
		{
			if (MessageBox.Show(
			        "Open pokemon slots Hidden Grotto spreadsheet in web browser?", "Visit", MessageBoxButtons.YesNo, MessageBoxIcon.Asterisk
			    ) == DialogResult.Yes)
			{
				System.Diagnostics.Process.Start("https://sites.google.com/site/pokemonslots/gen-v/hidden-grottos");
			}
		}
		void Exit_butClick(object sender, EventArgs e)
		{
			this.Close();
		}

	}
}
